export const ADD_CURRENT_FORECAST = "ADD_CURRENT_FORECAST"
export const ADD_FORECAST_DETAIL = "ADD_FORECAST_DETAIL"
export const ADD_WEEKLY_FORECAST = "ADD_WEEKLY_FORECAST"
export const ADD_TEMPERATURE_RANGE = "ADD_TEMPERATURE_RANGE"